# Generated by Django 3.0.7 on 2020-06-14 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart',
            new_name='scart',
        ),
    ]
