# Generated by Django 3.0.7 on 2020-06-14 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200614_0744'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='scart',
            new_name='cart',
        ),
    ]
