# Generated by Django 3.0.7 on 2020-06-15 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200614_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='pcart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('payment', models.BooleanField()),
            ],
        ),
    ]
